robots:
  - T01:
      x: 1.0
      y: 1.5
  - T02:
      x: 2.0
      y: 1.5
  - tello1:
      x: 3.0
      y: 1.5
  # - T01
  # - T02
  # - tello1

uwb_nodes:
  T01:
    num_antennas: 3
    names: [
      "A", "B", "C",
    ]
    positions: [
      [0.5, 0.5, 0], [0.5, 0, 0], [0, 0.5, 0]
    ]
  T02:
    num_antennas: 2
    names: [
      "A", "B",
    ]
  tello1:
    num_antennas: 1
    names: [
      "A",
    ]
    positions: [
      [0.4, 0.6, 0]
    ]

uwb_ranges:
  # ground truth could be all to measure the distance between all the robots antennas or the robot that is supposed to be the ground truth
  ground_truth: "T01"
  type_measurement: "origin"
  localization_method: "lse"
  write_to_file: true
  max_twr_freq: 400
  duty_cycle: 1
  mean: 0.0
  std_dev: 0.1
  ranges: [
    "T02", "tello1",
  ]