robots: [
  "T01",
  "T02",
  "tello1",
  "tello2",
]

uwb_nodes:
  T01:
    num_antennas: 4
    names: [
      "A",
      "B",
      "C",
      "D",
    ]
  T02:
    num_antennas: 2
    names: [
      "A",
      "B",
    ]
  tello1:
    num_antennas: 2
    names: [
      "A",
      "B",
    ]
  tello2:
    num_antennas: 2
    names: [
      "A",
      "B",
    ]

uwb_ranges:
  ground_truth: "T01"
  max_twr_freq: 400
  duty_cycle: 1
  ranges: [
    "T02"
  ]