robots:
  - T01:
      x: 1.0
      y: 1.5
  - T02:
      x: 2.0
      y: 1.5
  # - T03:
  #     x: 4.0
  #     y: 1.5
  - tello1:
      x: 1.5
      y: 8.0
  - tello2:
      x: 3
      y: 4.0
  # - T01
  # - T02
  # - tello1

uwb_nodes:
  global_anchors: 
    num_antennas: 3
    names: [
      "A", "B", "C", "D"
    ]
    positions: [
      [-4.0, 4.0, 0.0], [4.0, 4.0, 0.0], [4.0, -4.0, 0.0], [-4.0, -4.0, 0.0]
    ]
  T01:
    num_antennas: 1
    names: [
      "A"
    ]
    positions: [
      [0.5, 0.5, 0]
    ]
  T02:
    num_antennas: 1
    names: [
      "A"
    ]
    positions: [
      [0.5, 0.5, 0]
    ]
  # T03:
  #   num_antennas: 1
  #   names: [
  #     "A",
  #   ]
  #   positions: [
  #     [0.5, 0.5, 0],
  #   ]
  tello1:
    num_antennas: 1
    names: [
      "A"
    ]
    positions: [
      [0.5, 0.5, 0]
    ]
  tello2:
    num_antennas: 1
    names: [
      "A"
    ]
    positions: [
      [0.5, 0.5, 0]
    ]

uwb_ranges:
  # ground truth could be "all" to measure the distance between all the robots antennas or the robot that is supposed to be the ground truth
  
  # To use trilateration, the type_measurement must be all
  ground_truth: "global_anchors"
  type_measurement: "all"
  localization_method: "trilat"
  write_to_file: False
  max_twr_freq: 400
  duty_cycle: 1
  mean: 0.0
  std_dev: 0.1
  ranges: [
    "T02", "tello1", "tello2"
  ]
demo_trajectory: False